export const customerData = [
  {
    name: "Jane Doe",
    number: "555-123-4567",
    email: "jane.doe@example.com",
    address: "123 Maple Street",
    city: "New York",
    state: "NY",
    zip: "10001",
    location: "Manhattan",
    referralCode: "REF12345",
  },
  {
    name: "John Smith",
    number: "555-987-6543",
    email: "john.smith@example.com",
    address: "45 Palm Avenue",
    city: "Los Angeles",
    state: "CA",
    zip: "90001",
    location: "Downtown LA",
    referralCode: "REF67890",
  },
  {
    name: "Mary Johnson",
    number: "555-321-0987",
    email: "mary.johnson@example.com",
    address: "7 Broad Street",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    location: "The Loop",
    referralCode: "REF54321",
  },
  {
    name: "Michael Brown",
    number: "555-765-4321",
    email: "michael.brown@example.com",
    address: null,
    city: null,
    state: null,
    zip: null,
    location: "Houston",
    referralCode: "REF98765",
  },
  {
    name: "Emily Davis",
    number: "555-112-2334",
    email: "emily.davis@example.com",
    address: "22 Oak Lane",
    city: "Phoenix",
    state: "AZ",
    zip: "85001",
    location: "Downtown",
    referralCode: "REF19283",
  },
  {
    name: "David Wilson",
    number: "555-987-6123",
    email: "david.wilson@example.com",
    address: "89 Cedar Road",
    city: "San Antonio",
    state: "TX",
    zip: "78201",
    location: "Downtown",
    referralCode: "REF45678",
  },
  {
    name: "Olivia Martinez",
    number: "555-223-3445",
    email: "olivia.martinez@example.com",
    address: "14 Pine Street",
    city: "San Diego",
    state: "CA",
    zip: "92101",
    location: "Gaslamp Quarter",
    referralCode: "REF56473",
  },
  {
    name: "Daniel Garcia",
    number: "555-876-5432",
    email: "daniel.garcia@example.com",
    address: "67 Elm Street",
    city: "Dallas",
    state: "TX",
    zip: "75201",
    location: "Downtown",
    referralCode: "REF83729",
  },
  {
    name: "Sophia Rodriguez",
    number: "555-654-3210",
    email: "sophia.rodriguez@example.com",
    address: "33 Birch Avenue",
    city: "San Francisco",
    state: "CA",
    zip: "94101",
    location: "Mission District",
    referralCode: "REF39485",
  },
  {
    name: "James Anderson",
    number: "555-456-7890",
    email: "james.anderson@example.com",
    address: "77 Spruce Drive",
    city: "Seattle",
    state: "WA",
    zip: "98101",
    location: "Downtown",
    referralCode: "REF84938",
  },
];
